-- insert movie table

INSERT INTO cinema.movie(movýe_id, movie_title, movie_director, movie_cast, movie_duration, movie_description) values (1,'Aslan Kral', 'Jon Favreau', '(Chiwetel Ejiofor, John Oliver, James Earl Jones)','158','In Africa, the lion cub Simba is the pride and joy of his parents King Mufasa and Queen Sarabi. Mufasa prepares Simba to be the next king of the jungle. However, the naive Simba believes in his envious uncle Scar that wants to kill Mufasa and Simba to become the next king.');

INSERT INTO cinema.movie(movýe_id, movie_title, movie_director, movie_cast, movie_duration, movie_description) values (2,'Aladdin', 'Guy Ritchie', '(Will Smith, Mena Massoud, Naomi Scott)','128','A kind-hearted street urchin Aladdin vies for the love of the beautiful princess Jasmine, the princess of Agrabah. When he finds a magic lamp, he uses the genies magic power to make himself a prince in order to marry her. He is also on a mission to stop the powerful Jafar who plots to steal the magic lamp that could make his deepest wishes come true.');

INSERT INTO cinema.movie(movýe_id, movie_title, movie_director, movie_cast, movie_duration, movie_description) values (3,'Parasite', 'Bong Joon Ho', '(Song Kang-Ho, Lee Sun-kyun, Cho Yeo-jeong)','132','The Kims - mother and father Chung-sook and Ki-taek, and their young adult offspring, son Ki-woo and daughter Ki-jung - are a poor family living in a shabby and cramped half basement apartment in a busy lower working class commercial district of Seoul. Without even knowing it, they, especially Mr. and Mrs. Kim, literally smell of poverty. Often as a collective, they perpetrate minor scams to get by, and even when they have jobs, they do the minimum work required. Ki-woo is the one who has dreams of getting out of poverty by one day going to university.');

INSERT INTO cinema.movie(movýe_id, movie_title, movie_director, movie_cast, movie_duration, movie_description) values (4,'Wonder Woman 1984', 'Patty Jenkins', '(Gal Gadot, Chris Pine, Kristen Wiig)','151','Diana must contend with a work colleague and businessman, whose desire for extreme wealth sends the world down a path of destruction, after an ancient artifact that grants wishes goes missing.');

INSERT INTO cinema.movie(movýe_id, movie_title, movie_director, movie_cast, movie_duration, movie_description) values (5,'Tenet', 'Christopher Nolan', '(Juhan Ulfsak, Jefferson Hall, Ivo Uukkivi)','150','In a twilight world of international espionage, an unnamed CIA operative, known as The Protagonist, is recruited by a mysterious organization called Tenet to participate in a global assignment that unfolds beyond real time. The mission: prevent Andrei Sator, a renegade Russian oligarch with precognition abilities, from starting World War III. The Protagonist will soon master the art of "time inversion" as a way of countering the threat that is to come.');

INSERT INTO cinema.movie(movýe_id, movie_title, movie_director, movie_cast, movie_duration, movie_description) values (6,'Avengers:Endgame', '(Anthony Russo, Joe Russo)', '(Robert Downey Jr., Chris Evans, Mark Ruffalo, Chris Hemsworth, Scarlett Johansson, Jeremy Renner, Don Cheadle, Paul Rudd, Benedict Cumberbatch, Chadwick Boseman, Brie Larson, Tom Holland)','181','After the devastating events of Avengers: Infinity War (2018), the universe is in ruins due to the efforts of the Mad Titan, Thanos. With the help of remaining allies, the Avengers must assemble once more in order to undo Thanos is actions and undo the chaos to the universe, no matter what consequences may be in store, and no matter who they face...');

INSERT INTO cinema.movie(movýe_id, movie_title, movie_director, movie_cast, movie_duration, movie_description) values (7,'Outside the Wire', 'Mikael Håfström', '(Anthony Mackie, Enzo Cilenti, Michael Kelly)','114','When disgraced drone pilot, Lt. Harp (Damson Idris) is sent into a deadly militarized zone after disobeying orders, he finds himself working for Capt. Leo (Anthony Mackie), an android officer tasked with locating a doomsday device before insurgents do.');

INSERT INTO cinema.movie(movýe_id, movie_title, movie_director, movie_cast, movie_duration, movie_description) values (8,'Nomadland', 'Chloé Zhao', '(Frances McDormand, Gay DeForest, Patricia Grier)','108','Following the economic collapse of a company town in rural Nevada, Fern (Frances McDormand) packs her van and sets off on the road exploring a life outside of conventional society as a modern-day nomad. The third feature film from director Chloé Zhao, NOMADLAND features real nomads Linda May, Swankie and Bob Wells as Fern is mentors and comrades in her exploration through the vast landscape of the American West.');

INSERT INTO cinema.movie(movýe_id, movie_title, movie_director, movie_cast, movie_duration, movie_description) values (9,'The Gentlemen', 'Guy Ritchie', '(	Matthew McConaughey, Charlie Hunnam, Michelle Dockery)','113','A talented American graduate of Oxford, using his unique skills, and audacity, creates a marijuana empire using the estates of impoverished British aristocrats. However, when he tries to sell his empire to a fellow American billionaire, a chain of events unfolds, involving blackmail, deception, mayhem and murder between street thugs, Russian oligarchs, Triad gangsters and gutter journalists.');

INSERT INTO cinema.movie(movýe_id, movie_title, movie_director, movie_cast, movie_duration, movie_description) values (10,'Mulan', 'Niki Caro', '(Yifei Liu, Donnie Yen, Li Gong)','115','A young Chinese maiden disguises herself as a male warrior in order to save her father.');

INSERT INTO cinema.movie(movýe_id, movie_title, movie_director, movie_cast, movie_duration, movie_description) values (11,'News of the World', 'Paul Greengrass', '(Tom Hanks, Steve Boyles, Helena Zengel, Tom Astor)','118','Five years after the end of the Civil War, Captain Jefferson Kyle Kidd (Tom Hanks), a veteran of three wars, now moves from town to town as a non-fiction storyteller, sharing the news of presidents and queens, glorious feuds, devastating catastrophes, and gripping adventures from the far reaches of the globe. On the plains of Texas, he crosses paths with Johanna (Helena Zengel), a 10-year-old taken in by the Kiowa people six years earlier and raised as one of their own. Johanna, hostile to a world she is never experienced, is being returned to her biological aunt and uncle against her will. Kidd agrees to deliver the child where the law says she belongs. As they travel hundreds of miles into the unforgiving wilderness, the two will face tremendous challenges of both human and natural forces as they search for a place that either can call home.');

INSERT INTO cinema.movie(movýe_id, movie_title, movie_director, movie_cast, movie_duration, movie_description) values (12,'Knives Out', 'Rian Johnson', '(Daniel Craig, Chris Evans, Ana de Armas, Jamie Lee Curtis)','130','When renowned crime novelist Harlan Thrombey (Christopher Plummer) is found dead at his estate just after his 85th birthday, the inquisitive and debonair Detective Benoit Blanc (Daniel Craig) is mysteriously enlisted to investigate. From Harlan is disfunctional family to his devoted staff, Blanc sifts through a web of red herrings and self-serving lies to uncover the truth behind Harlan is untimely death.');

INSERT INTO cinema.movie(movýe_id, movie_title, movie_director, movie_cast, movie_duration, movie_description) values (13,'Greenland', 'Ric Roman Waugh', '(Gerard Butler, Morena Baccarin, Roger Dale Floyd)','119','A family fights for survival as a planet-killing comet races to Earth. John Garrity (Gerard Butler), his estranged wife Allison (Morena Baccarin), and young son Nathan make a perilous journey to their only hope for sanctuary. Amid terrifying news accounts of cities around the world being leveled by the comet is fragments, the Garritys experience the best and worst in humanity while they battle the increasing panic and lawlessness surrounding them. As the countdown to global apocalypse approaches zero, their incredible trek culminates in a desperate and last-minute flight to a possible safe haven.');

INSERT INTO cinema.movie(movýe_id, movie_title, movie_director, movie_cast, movie_duration, movie_description) values (14,'Soul', '(Pete Docter, Kemp Powers )', '(Jamie Foxx, Tina Fey, Graham Norton)','100','Joe is a middle-school band teacher whose life has not quite gone the way he expected. His true passion is jazz and he is good. But when he travels to another realm to help someone find their passion, he soon discovers what it means to have soul.');

INSERT INTO cinema.movie(movýe_id, movie_title, movie_director, movie_cast, movie_duration, movie_description) values (15,'Pieces of a Woman', 'Kornél Mundruczó', '(Vanessa Kirby, Shia LaBeouf, Ellen Burstyn)','126','Martha and Sean are a Boston couple on the verge of parenthood whose lives change irrevocably when a home birth ends in unimaginable tragedy. Thus begins a yearlong odyssey for Martha, who must navigate her grief while working through fractious relationships with her husband and her domineering mother, along with the publicly vilified midwife, whom she must face in court. A deeply personal, searing, and ultimately transcendent story of a woman learning to live alongside her loss.');

INSERT INTO cinema.movie(movýe_id, movie_title, movie_director, movie_cast, movie_duration, movie_description) values (16,'The Midnight Sky', 'George Clooney', '(George Clooney, Felicity Jones, David Oyelowo)','118','A scientist is working alone at a remote Arctic research station when he learns of a mysterious global disaster. At the same time, he meets a strange girl in the Arctic, with whom he must stop the return to Earth of the crew of the spaceship "Ether".');

INSERT INTO cinema.movie(movýe_id, movie_title, movie_director, movie_cast, movie_duration, movie_description) values (17,'Promising Young Woman', 'Emerald Fennell', '(Adam Brody, Ray Nicholson,Sam Richardson)','113','A young woman, traumatized by a tragic event in her past, seeks out vengeance against those who crossed her path.');

INSERT INTO cinema.movie(movýe_id, movie_title, movie_director, movie_cast, movie_duration, movie_description) values (18,'We Can Be Heroes', 'Robert Rodriguez', '(YaYa Gosselin, Lyon Daniels, Andy Walken, Hala Finley)','100','When alien invaders kidnap Earth is superheroes, their kids are whisked away to a government safe house. But whip-smart tween Missy Moreno will stop at nothing to rescue her superhero dad, Marcus Moreno. Missy teams up with the rest of the superkids to escape their mysterious government babysitter, Ms. Granada. If they are going to save their parents, they will have to work together by using their individual powers - from elasticity to time control to predicting the future - and form an out-of-this-world team.');

INSERT INTO cinema.movie(movýe_id, movie_title, movie_director, movie_cast, movie_duration, movie_description) values (19,'Locked Down', 'Doug Liman', '(Sonic, Chiwetel Ejiofor, Dulé Hill)','118','A couple attempts a high-risk, high-stakes jewelry heist at a department store.');

INSERT INTO cinema.movie(movýe_id, movie_title, movie_director, movie_cast, movie_duration, movie_description) values (20,'Druk', 'Thomas Vinterberg', '(Mads Mikkelsen, Thomas Bo Larsen, Magnus Millang)','117','There is a theory that man is born with half a per mille too little. That alcohol in the blood opens the mind to the outside world, problems seem smaller and creativity increases. We know it well; after the first glass of wine, the conversation lifts, the possibilities open up. Martin is a high school teacher. He feels old and tired. His students and their parents want him terminated to increase their average. Encouraged by the per mille theory, Martin and his three colleagues throw themselves into an experiment to maintain a constant alcohol impact in everyday life. If Churchill won World War II in a dense fog of spirits, what could the strong drops do for them and their students? The result is positive in the beginning. ');

INSERT INTO cinema.movie(movýe_id, movie_title, movie_director, movie_cast, movie_duration, movie_description) values (21,'Run', 'Aneesh Chagantyu', '(,Sarah Paulson, Kiera Allen, Sara Sohn)','90','Chloe, a teenager who is confined to a wheelchair, is home schooled by her mother, However, her mother is strange behavior does not go unnoticed and when Chloe pries into some private papers, she discovers a Change of Name Certificate document with her mother is name, Diane Sherman, on it. When Chloe googles "Diane Sherman," the internet suddenly disconnnects. Chloe becomes suspicious of all that her mother does, suspecting her of something sinister. She decides to go on the run in her wheelchair in a desperate attempt to get away from her.');

INSERT INTO cinema.movie(movýe_id, movie_title, movie_director, movie_cast, movie_duration, movie_description) values (22,'The Croods: A New Age', 'Joel Crawford', '(Nicolas Cage, Emma Stone, Ryan Reynolds, Catherine Keener, Cloris Leachman)','95','The prehistoric family the Croods are challenged by a rival family the Bettermans, who claim to be better and more evolved.');

INSERT INTO cinema.movie(movýe_id, movie_title, movie_director, movie_cast, movie_duration, movie_description) values (23,'Ma Rainey is Black Bottom', 'George C. Wolfe', '(Chiwetel Ejiofor, John Oliver, James Earl Jones)','94','Tensions and temperatures rise over the course of an afternoon recording session in 1920s Chicago as a band of musicians await trailblazing performer, the legendary "Mother of the Blues," Ma Rainey (Academy Award® winner Viola Davis). Late to the session, the fearless, fiery Ma engages in a battle of wills with her white manager and producer over control of her music. As the band waits in the studio is claustrophobic rehearsal room, ambitious trumpeter Levee (Chadwick Boseman) - who has an eye for Ma is girlfriend and is determined to stake his own claim on the music industry - spurs his fellow musicians into an eruption of stories revealing truths that will forever change the course of their lives.');

INSERT INTO cinema.movie(movýe_id, movie_title, movie_director, movie_cast, movie_duration, movie_description) values (24,'1917', 'Sam Mendes', '(Dean-Charles Chapman, George MacKay, Daniel Mays)','119','April 1917, the Western Front. Two British soldiers are sent to deliver an urgent message to an isolated regiment. If the message is not received in time the regiment will walk into a trap and be massacred. To get to the regiment they will need to cross through enemy territory. Time is of the essence and the journey will be fraught with danger.');

INSERT INTO cinema.movie(movýe_id, movie_title, movie_director, movie_cast, movie_duration, movie_description) values (25,'The Trial of the Chicago 7', 'Aaron Sorkin', '(Eddie Redmayne, Alex Sharp, Sacha Baron Cohen)','129','In Chicago 1968, the Democratic Party Convention was met with protests from activists like the moderate Students for a Democratic Society led by Tom Hayden and the militant Yippies led by Abbie Hoffman and Jerry Rubin, which led to violent confrontations with the local authorities. As a result, seven of the accused ringleaders are arraigned on charges like Conspiracy by the hostile Nixon administration, including Bobby Seale of the Black Panthers who was not involved in the incident. What follows is an unfair trial presided by the belligerent Judge Hoffman (No relation) and prosecuted by a reluctant but duty-bound Richard Schultz.');






